import { test, expect } from '@playwright/test';
import { ALL_SPECS, loadManifest, specResults } from './bustedHarness';
import { KNOWN_DIVERGENCES, UNSUPPORTED_AREAS, knownDivergence } from './knownDivergences';

// Mudlet's busted *_spec.lua suite, run against the real mudix app in a browser.
// This is the single path for the whole corpus: because the live app wires the
// full ScriptingEngine (trigger/alias dispatch, timer pump) and renders real
// overlay/Geyser geometry, specs the node thin-layer couldn't exercise (triggers
// via feedTriggers, DOM-dependent widgets) run here too.
//
// Each Mudlet it() is registered as its own Playwright test() so IDE runners
// (WebStorm/VS Code) and JUnit list every individual test as a first-class,
// re-runnable node — not just one row per spec. The test tree must be known at
// collection time (before any browser runs), so the it() names come from a
// committed manifest (e2e/busted.manifest.json) generated by genBustedManifest.ts.
// A per-spec drift guard fails loudly if the live it() set diverges from it.

const manifest = loadManifest();

// ── Per-test suite: one Playwright test() per Mudlet it() ────────────────────
for (const spec of ALL_SPECS) {
    const names = manifest[spec];
    if (!names || names.length === 0) continue; // manifest not generated yet

    test.describe(`${spec}_spec`, () => {
        names.forEach((name, idx) => {
            // Occurrence index disambiguates the rare case of two it()s sharing a
            // full name, so each test() title is unique and maps to the right run.
            const occ = names.slice(0, idx + 1).filter(n => n === name).length;
            const title = occ === 1 ? name : `${name} (#${occ})`;

            test(title, async ({ page }) => {
                // An assertion mudix deliberately does not satisfy is marked
                // expected-to-fail rather than skipped, so the day it starts
                // passing is a red run telling us to delete the entry — see
                // knownDivergences.ts.
                const divergence = knownDivergence(spec, name);
                if (divergence) test.fail(true, `known divergence: ${divergence.reason}`);

                const r = await specResults(page, spec);
                const t = r.tests.filter(x => x.name === name)[occ - 1];
                expect(
                    t,
                    `"${name}" not in live run — manifest drift; run \`npm run gen:busted-manifest\``,
                ).toBeTruthy();
                if (t.status === 'pending') {
                    test.skip(true, 'pending upstream stub');
                    return;
                }
                expect(t.status, t.message || name).toBe('success');
            });
        });
    });
}

// ── Drift guard: the manifest must match the live it() set, per spec ─────────
// Catches specs re-synced (or APIs changed) without regenerating the manifest:
// without this, an added/removed/renamed it() would silently never run. Also
// catches errors raised outside any it() (load/describe/setup failures), which
// never produce a test record and would otherwise dodge the per-test assertions.
test.describe('manifest drift guard', () => {
    for (const spec of ALL_SPECS) {
        test(`${spec}: manifest matches live it() set`, async ({ page }) => {
            const r = await specResults(page, spec);
            const live = r.tests.map(t => t.name).sort();
            const recorded = (manifest[spec] ?? []).slice().sort();
            expect(
                live,
                `${spec} it() set drifted from manifest — run \`npm run gen:busted-manifest\``,
            ).toEqual(recorded);
            expect(r.errors, `${spec}: ${r.errors} error(s) outside any it()`).toBe(0);
        });
    }
});

// ── Divergence guard: every recorded divergence must still name a live it() ──
// Without this, an it() renamed or dropped upstream would leave a dead entry in
// knownDivergences.ts — and dead entries are worse than none: the next person
// reads the list as the complete account of where mudix differs from Mudlet, and
// a stale line makes that account wrong. Checked against the manifest rather than
// a live run so it costs nothing (the manifest is the committed it() set, and the
// drift guard above already proves it matches reality).
// ── Unsupported areas still skip for the reason we recorded ─────────────────
// A whole area that cannot run here skips rather than fails, which makes it look
// exactly like an area whose fixture we simply have not started. The entry in
// knownDivergences.ts is what tells those apart — so it has to keep matching
// something. When it stops, either upstream rewrote the gate or the capability
// arrived, and both are worth a look rather than a silently wrong note.
test.describe('unsupported areas', () => {
    for (const area of UNSUPPORTED_AREAS) {
        test(`${area.area} still skips for the recorded reason`, async ({ page }) => {
            const r = await specResults(page, area.spec);
            const matching = r.tests.filter(t =>
                t.status === 'pending' && (t.message ?? '').includes(area.pendingReason));
            expect(
                matching.length,
                `No ${area.spec} test skips with "${area.pendingReason}" any more. Either the capability `
                + `arrived or upstream changed the gate — update or remove this entry in `
                + `e2e/knownDivergences.ts rather than leaving it describing something that no longer happens.`,
            ).toBeGreaterThan(0);
        });
    }
});

test('known divergences all name a live spec', () => {
    const manifest = loadManifest();
    const dead: string[] = [];
    for (const [spec, divergences] of Object.entries(KNOWN_DIVERGENCES)) {
        const names = new Set(manifest[spec] ?? []);
        for (const d of divergences) {
            if (!names.has(d.name)) dead.push(`${spec}: "${d.name}"`);
        }
    }
    expect(
        dead,
        'knownDivergences.ts names it()s that no longer exist — the spec was renamed or dropped '
        + 'upstream, so the entry is now hiding nothing and should be removed:\n  ' + dead.join('\n  '),
    ).toEqual([]);
});
